### ISSUE TITLE
The plugin does not check some rules

### ISSUE THREAD

**Issue by gyuwon** [ec4j/editorconfig-gradle-plugin#14]
In this simple project https://github.com/gyuwon/editorconfig-java, `Library.java` file has several rule violations but the command `gradle editorconfigCheck` checks only the rule `trim_trailing_whitespace = true`. The following rules are ignored.

```java
package editorconf;

public class Library {
      public boolean someLibraryMethod() {
            return true;    
	}
}
```

- `indent_style = space`
- `indent_size = 4`
- `insert_final_newline = true`

How can I fix it?

**Comment by gyuwon** [comment]
This is the output

```text
> gradle editorconfigCheck

> Task :editorconfigCheck FAILED
src\main\java\editorconf\Library.java@5,25: Delete 4 characters - violates trim_trailing_whitespace = true, reported by org.ec4j.maven.linters.TextLinter

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':editorconfigCheck'.
> There are .editorconfig violations. You may want to run

      ./gradlew editorconfigFormat

  to fix them automagically.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed
```

**Comment by ppalaga** [comment]
Much like [ec4j Maven plugin](https://ec4j.github.io/editorconfig-maven-plugin/#how_it_works), the Gradle plugin is is designed around the Linter interface. Linter is a processor specialized for some particular file format (such as YAML or XML) for which it can detect whether some particular .editorconfig properties are satisfied and eventually propose a fix that can be applied automatically.

As you may guess, there is no Linter for Java files yet.

**Comment by gyuwon** [comment]
@ppalaga Thanks for the explanation. I'm closing this issue.
