### ISSUE TITLE
cannot download

### ISSUE THREAD

**Issue by Zougi** [ec4j/editorconfig-gradle-plugin#2]
Hey! I would love to try this plugin. However I'm getting the following issue:

```
$ gradle editorconfigCheck

FAILURE: Build failed with an exception.

* Where:
Build file '/somefolder/build.gradle' line: 19

* What went wrong:
Plugin [id: 'org.ec4j.editorconfig'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

All I did was to add plugin to the plugin block

```
plugins {
    id 'org.ec4j.editorconfig'
}
```

I also tried to tell gradle to look in sonatype stage repo.

```
repositories {
    mavenLocal()
    maven { url 'https://oss.sonatype.org/service/local/staging/deploy/maven2/' }
    jcenter()
    mavenCentral()
}
```

No luck with that.
I then specified the version 0.0.1, I got this error

```
$ gradle editorconfigCheck

FAILURE: Build failed with an exception.

* Where:
Build file '/somefolder/build.gradle' line: 19

* What went wrong:
Plugin [id: 'org.ec4j.editorconfig', version: '0.0.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.ec4j.editorconfig:org.ec4j.editorconfig.gradle.plugin:0.0.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

```

this error tells artifact group should be `org.ec4j.editorconfig` but another group is defined in gradle.build of this repository. Could it be the issue? I looked in gradle.build documentation but couldn't find a way to specify the artifact group from the plugin block.

**Comment by ppalaga** [comment]
Hi @Zougi, nice to hear about your interest. It cannot work, because I have not released the plugin yet. I think I'll be able to release within a couple of days and once I manage to release, I'll give you a notice here.

**Comment by ppalaga** [comment]
I released 0.0.1 to gradle plugin portal https://plugins.gradle.org/plugin/org.ec4j.editorconfig
Please share here if you feel something does not work properly.

**Comment by Zougi** [comment]
Thanks for releasing the plugin! I could install the plugin with the classpath + apply plugin method!
However fyi

```
plugins {
  id "org.ec4j.editorconfig" version "0.0.1"
}
```

above method didn't work with gradle 4.5 on macos

**Comment by ppalaga** [comment]
Strange, I thought, plugins {} was the newest and most preferred method. I should add a test with the newest Gradle.

**Comment by ppalaga** [comment]
See https://github.com/ec4j/editorconfig-gradle-plugin/issues/5
