### ISSUE TITLE
needs license for scans

### ISSUE THREAD

**Issue by Johnlon** [ec4j/editorconfig-gradle-plugin#26]

**Comment by ppalaga** [comment]
Could you please provide more details what you mean?

**Comment by Johnlon** [comment]
Does the distribution have an embedded licence where it's is typically placed? ( where scanning tools expect it?)

**Comment by ppalaga** [comment]
Could you please be even more specific? What is "distance"? Where does your scanning tool expect the license?

**Comment by Johnlon** [comment]
Sorry fixed typos in previous comments

**Comment by ppalaga** [comment]
Where does your scanning tool expect the license?

**Comment by Johnlon** [comment]
If you use the usual maven gradle builder stuff it will put it in proper place

**Comment by ppalaga** [comment]
Where does your scanning tool expect the license?

**Comment by Johnlon** [comment]
Hi if you use the maven/ gradle plugin it's clear

**Comment by ppalaga** [comment]
Please feel free to reopen when you are ready to provide the requested information.
