### ISSUE TITLE
plugins {} install does not work on gradle 4.5 on macos

### ISSUE THREAD

**Issue by ppalaga** [ec4j/editorconfig-gradle-plugin#5]
Reported by @Zougi

I could install the plugin with the classpath + apply plugin method!
However fyi

```
plugins {
  id "org.ec4j.editorconfig" version "0.0.1"
}
```

above method didn't work with gradle 4.5 on macos

**Comment by Zougi** [comment]
I cannot reproduce the issue on gradle 4.5.1

I also put version 4.5.1 instead of 4.2.12 in my gradle wrapper (this should not be linked but idk)

```
task wrapper(type: Wrapper) {
   gradleVersion = '4.2.12'
}
```

I believe we can close the issue

**Comment by ppalaga** [comment]
Good to know, thanks!
